name: Docker

on:
  push:
    paths-ignore: [ '**.md' ]
  pull_request:
    paths-ignore: [ '**.md' ]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - image: "github-backup"
            platforms: linux/amd64,linux/arm64
          - image: "offlineimap"
            platforms: linux/amd64,linux/arm64
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: dioptra-io/publish-docker-action@v1.3
        with:
          context: ${{ matrix.image }}
          file: ${{ matrix.image }}/Dockerfile
          image: maxmouchet/docker-images/${{ matrix.image }}
          password: ${{ secrets.GITHUB_TOKEN }}
          platforms: ${{ matrix.platforms }}
